name: "Fetch recent pharmacies from OpenStreetMap"
on:
  schedule:
    # Each day at 0:00AM
    - cron: '0 0 1 * *'
  # Trigger fetch on demand
  repository_dispatch:
    types: [fetch-latest-pharmacies-osm]
  workflow_dispatch:
jobs:
  pull_data_osm:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v6
      - name: 🔨 Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: 🚧 Install dependencies
        run: pip3 install -r requirements.txt
      - name: 🤖 Fetch pharmacies from OSM
        run: python3 scripts/pharmaciesFromOSM.py
      - name: 📄 Retrieve modified or new JSON file
        uses: dorny/paths-filter@v4.0.1
        id: git_diff
        with:
          base: HEAD
          ref: ${{ github.ref }}
          token: ${{ github.token }}
          list-files: "shell"
          filters: |
            data:
              - added|modified: '*.json'
# Maximal one file should match criteria
# Maybe later improve the updateStats.py to take multiple arguments ?
      - name: ✉️ Commit new files to Github
        if: ${{ steps.git_diff.outputs.data == 'true' }}
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore(script): apply automatic changes"
          file_pattern: '*.json'
          commit_user_name: "BE pharmacies list updater Bot"
      - name: 💤 Skip job
        if: ${{ steps.git_diff.outputs.data == 'false' }}
        run: echo "No modified / added JSON file - See you later"
